apiVersion: v1
kind: ConfigMap
metadata:
  name: threat-intel-config
  namespace: threat-intel
data:
  # Neo4j Configuration
  NEO4J_URI: "bolt://neo4j-service:7687"
  NEO4J_DATABASE: "threat_intelligence"
  
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_TITLE: "Threat Intelligence Graph API"
  API_VERSION: "1.0.0"
  DEBUG: "false"
  
  # Kafka Configuration
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_TOPIC_THREAT_INTEL: "threat_intelligence"
  KAFKA_TOPIC_IOC_CORRELATION: "ioc_correlation"
  
  # Logging
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"



